services:
  dev_cont:
    build:
      context: .
      dockerfile: dockerfile
    container_name: my_devcontainer
    volumes:
      - ./projects/:/root/projects
      - devenv:/etc/devenv
      - nvim-plugin:/root/.local/share/nvim
      - nvim-cache:/root/.cache/nvim
    tty: true

volumes:
  devenv:
  nvim-plugin:
  nvim-cache: